// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrppnrokisoxmaznylsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycHBucm9raXNveG1hem55bHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTY2NTIsImV4cCI6MjA3MjE5MjY1Mn0.1TtJAr-dkQ_39nxVLj4XRz3hZ7CEyMaw6wUZVoiV3Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});